# docker build --rm -t kungfu-ci-base:snapshot -f .github/Dockerfile.base .
FROM github-ci-base:latest

WORKDIR /src/kungfu
ADD . .

RUN pip3 install --no-index -U -v .

ENV GOBIN /root/go/bin
RUN go install -v ./tests/go/cmd/...
ENV PATH ${GOBIN}:${PATH}
