language: go

# https://docs.travis-ci.com/user/reference/bionic/#using-ubuntu-1804-bionic-beaver
dist: bionic

# https://docs.travis-ci.com/user/languages/go/#specifying-a-go-version-to-use
go:
- 1.11.x

script:
- go test -v ./...
- ./configure --build-tests
- make
- make test
