#!/bin/sh
set -e

. ./scripts/utils/measure.sh
# go install -v ./...

find_python() {
    if [ $(basename $(realpath $PWD/../..)) = "mindspore" ]; then
        which python3.7
    else
        which python3
    fi
}

PYTHON=$(find_python)

echo "Using $PYTHON"

export KUNGFU_ENABLE_MINDSPORE_ELASTIC=1

measure $PYTHON -m pip install --no-index -U .

echo "done $0"
