FROM swr.cn-north-1.myhuaweicloud.com/mailuo/kungfu-huawei-builder:v.10

# Add the KungFu sources
ADD . /KungFu

# Install KungFu
RUN cd /KungFu && \
        ldconfig /usr/local/cuda-9.0/targets/x86_64-linux/lib/stubs && \
        env KUNGFU_USE_NCCL=1 pip install --no-index --user -U . && \
        ldconfig && \
        ./scripts/go-install.sh

WORKDIR /