FROM swr.cn-north-1.myhuaweicloud.com/mailuo/kungfu-huawei-builder:v.1

# Install tensorflow-gpu 1.12.0
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorflow-gpu==1.12.0

# Add the KungFu sources
ADD . /KungFu

# Install KungFu
RUN cd /KungFu && \
        ldconfig /usr/local/cuda-9.0/targets/x86_64-linux/lib/stubs && \
        env KUNGFU_USE_NCCL=1 pip install --no-index --user -U . && \
        ldconfig && \
        ./scripts/go-install.sh

WORKDIR /