FROM tensorflow/tensorflow:1.13.1-py3

RUN apt update && apt install -y cmake wget
RUN wget -q https://dl.google.com/go/go1.13.linux-amd64.tar.gz && \
    tar -C /usr/local -xf go1.13.linux-amd64.tar.gz && \
    rm go1.13.linux-amd64.tar.gz
ENV PATH=${PATH}:/usr/local/go/bin

ADD . /src/kungfu
WORKDIR /src/kungfu

RUN pip3 install --no-index -U .
RUN GOBIN=/usr/bin go install -v ./srcs/go/cmd/kungfu-run
