# docker image for build kungfu tools

FROM ubuntu:bionic AS builder

#ARG SOURCES_LIST=docker/sources.list.aliyun
#ADD ${SOURCES_LIST} /etc/apt/sources.list
RUN apt update && apt install -y build-essential cmake wget

RUN wget -q https://dl.google.com/go/go1.11.linux-amd64.tar.gz && \
    tar -C /usr/local -xf go1.11.linux-amd64.tar.gz && \
    rm go1.11.linux-amd64.tar.gz

ENV PATH=${PATH}:/usr/local/go/bin

ADD . /src/kungfu
WORKDIR /src/kungfu

RUN ./configure --build-tools && make
