FROM swr.cn-north-1.myhuaweicloud.com/eiwizard/custom-gpu-cuda9-inner-moxing-cp36:1.1 as base

# Fix the source lists
ARG SOURCES_LIST=docker/sources.list.aliyun
ADD ${SOURCES_LIST} /etc/apt/sources.list

# The pip source has been pre-configured to an internal source. Roll back to public sources.
RUN rm $HOME/.pip/pip.conf

# Add the NVIDIA package repo and fetch key
# Reference: https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/base/Dockerfile#L4
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates apt-transport-https gnupg-curl && \
    rm -rf /var/lib/apt/lists/* && \
    NVIDIA_GPGKEY_SUM=d1be581509378368edeec8c1eb2958702feedf3bc3d17011adbf24efacce4ab5 && \
    NVIDIA_GPGKEY_FPR=ae09fe4bbd223a84b2ccfce3f60f4b3d7fa2af80 && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub && \
    apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +5 > cudasign.pub && \
    echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub && \
    echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

# Install the GPU support for TensorFlow 1.12 (CUDA 9)
# Reference: https://www.tensorflow.org/install/gpu
RUN apt update && apt install -y --no-install-recommends \
        build-essential \
        cuda9.0 \
        cuda-cublas-9-0 \
        cuda-cufft-9-0 \
        cuda-curand-9-0 \
        cuda-cusolver-9-0 \
        cuda-cusparse-9-0 \
        libcudnn7=7.2.1.38-1+cuda9.0 \
        libnccl2=2.4.2-1+cuda9.0 \
        libnccl-dev=2.4.2-1+cuda9.0 \
        cuda-command-line-tools-9-0 \
        cmake
        # && rm -rf /var/lib/apt/lists/*

# Install tensorflow-gpu 1.12.0 in the conda environment (pip has been redirected to conda pip)
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorflow-gpu==1.12.0
# RUN pip install tensorflow-gpu==1.12.0

RUN wget -q https://dl.google.com/go/go1.11.linux-amd64.tar.gz && tar -C /usr/local -xf go1.11.linux-amd64.tar.gz && rm go1.11.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

WORKDIR /