name: CI

on: [push]

jobs:
  build:

    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - run: nproc
    - run: ./configure
    - run: make

  compatiability test:
    name: Test on node ${{ matrix.tf_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        tf_version:
        - '1.12.3'
        - '1.13.2'
        - '1.15.0'

    steps:
    - uses: actions/checkout@v1

    - name: install TF
      run: pip3 install tensorflow==${{ matrix.tf_version }}
    - name: install
      run: pip3 install --no-index -U .
    - name: test
      run: python3 -m kungfu.tensorflow.v1.examples
    # FIXME: more tests
