name: Compatiability

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-18.04

        python:
        - '3.6'

        tensorflow:
        - '1.12.3'
        - '1.13.2'
        - '1.15.0'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow==${{ matrix.tensorflow }}

    - run: pip install --no-index -U .
    - run: python -m kungfu.tensorflow.v1.examples
    # FIXME: more tests
