name: Docker

on: [push, pull_request]

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - run: docker build --rm -t kungfu:example -f docker/Dockerfile.example-ubuntu18 .
    - run: docker run --rm -t kungfu:example python3 -m kungfu.info
